name: LiquidSpace API Client

on:
  push:
    branches-ignore:
      - 'main'
      - 'demo'
      - 'stage'
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-checks:
    name: Build Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-skip: ${{ steps.skip_check.outputs.should_skip }}
      build-php: ${{ steps.changes.outputs.php }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            php:
              - 'composer.lock'
              - '.env.test'
              - 'src/**'
              - 'tests/**'
              - '.github/workflows/main.yaml'

      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          cancel_others: 'true'

  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    container:
      image: chargifi/php-dev-alpine:latest
      env:
        COMPOSER_MEMORY_LIMIT: '-1'
    needs: build-checks
    if: ${{ needs.build-checks.outputs.should-skip != 'true' && needs.build-checks.outputs.build-php == 'true' }}
    timeout-minutes: 5
    outputs:
      should-skip: ${{ needs.build-checks.outputs.should-skip }}
    steps:
      - uses: actions/checkout@v3

      - name: Dependency Cache
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: |
            ./vendor/
            ./composer.lock
          # Unique per run, so that child jobs can re-use, needs to be per run as the composer classmap can change with src changes
          key: ${{ runner.os }}-api-${{ github.run_id }}

      - name: Composer Install
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: composer install --classmap-authoritative --no-progress --no-interaction --ignore-platform-reqs

  lint-php:
    name: Lint PHP
    runs-on: ubuntu-latest
    container:
      image: chargifi/php-dev-alpine:latest
      env:
        COMPOSER_MEMORY_LIMIT: '-1'
    needs: build-php
    if: ${{ needs.build-php.outputs.should-skip != 'true' }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Restore Dependency Cache
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: |
            ./vendor/
            ./composer.lock
          key: ${{ runner.os }}-api-${{ github.run_id }}

      - name: PHP Code Style Check
        id: phpcs
        run: composer phpcs

      - name: PHP Static Analysis
        id: php-static-analysis
        run: composer phpstan

  test-php:
    name: Test PHP
    runs-on: ubuntu-latest
    container:
      image: chargifi/php-dev-alpine:latest
      env:
        COMPOSER_MEMORY_LIMIT: '-1'
    needs: build-php
    if: ${{ needs.build-php.outputs.should-skip != 'true' }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Restore Dependency Cache
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: |
            ./vendor/
            ./composer.lock
          key: ${{ runner.os }}-api-${{ github.run_id }}

      - name: PHP Unit Tests
        id: php-unit-tests
        run: composer test
